# Generated by Django 2.2.26 on 2022-04-20 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=256)),
                ('line2', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('stateCode', models.CharField(max_length=4)),
                ('zipCode', models.CharField(max_length=16)),
                ('countryCode', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenName', models.CharField(max_length=256)),
                ('familyName', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=8)),
                ('dateOfBirth', models.DateField()),
                ('socialSecurityNumber', models.CharField(max_length=16)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_address', to='patients.Address')),
            ],
        ),
    ]
